### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by williamfzc** [williamfzc/pyminitouch#1]
- [x] support multi-point operation
- [x] higher level API
- [x] port check
- [x] the maximum X and Y usually do not match the display size
- [ ] pre-built package did not work sometimes
